
services:

  postgres:
    image: postgres:latest
    container_name: company_springboot_postgres
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_springboot_db
      PGDATA: /var/lib/data/postgresql

  company-springboot:
    build:
      context: company-springboot
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company_springboot_db

  proxy-server:
    build:
      context: proxy-server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - company-springboot
    ports:
      - "8765:8765"