


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:8765
Accept: application/json



### Company Requests



###
GET /api/v1/companies
Host: localhost:8765
Accept: application/json

###
GET /api/v1/companies/by-id?companyId=48e3110c-2ed8-4774-80a2-8bbffdd93681
Host: localhost:8765
Accept: application/json

###
POST /api/v1/companies/create-update
Host: localhost:8765
Accept: application/json
Content-Type: application/json

{
    "name": "TV Set Corporation",
    "description": "Описание компании TV Set Corporation"
}

###
POST /api/v1/companies/create-update
Host: localhost:8765
Accept: application/json
Content-Type: application/json

{
    "id": "7be8254d-9db5-4e75-90f1-6f6fa886d529",
    "name": "TV Set",
    "description": "Описание компании TV Set"
}

###
DELETE /api/v1/companies/delete?companyId=7be8254d-9db5-4e75-90f1-6f6fa886d529
Host: localhost:8765
Accept: application/json



### Identity Requests


###
GET /api/v1/identities
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/identities/by-id?identityId=f70c249a-d2c3-4b52-8c5e-b53cd3e9ae6d
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/identities
Host: localhost:8765
Accept: application/json

###
POST /api/v1/identities/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: fCfC1b6M23ey91vufqXhrfI0QaoDE6UWEh4txkDXp-jcOCoCTkPx5Iy8v0OfkW_dSIjVlcBXbJNhcpU7dy8Yo3S2k47qXRxk

{
    "authority": "DIRECTOR",
    "username": "director@gmail.com",
    "password": "director",
    "phone": "+7(956)-769-42-95",
    "firstname": "Бушуев",
    "lastname": "Виктор",
    "patronymic": "Валерьевич",
    "about": "Биография Бушуева В.В."
}

###
PUT /api/v1/identities/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: RSJQMT0-6POI_cC__Oiemnhn2uLHNWZJR4rVxDPs2uLhGN8dIxNjCQlcisely_iJzsWq_khX99ulAwVkf73j8QeIudCHeu94

{
    "id": "43aeaf10-3e2d-406e-bb78-2f3f9d7c3e4d",
    "firstname": "Валуев",
    "lastname": "Арсений",
    "patronymic": "Викторович",
    "about": "Биография Валуева А.В."
}

###
PUT /api/v1/identities/add-company?companyId=75d0df53-eca7-4aa1-b253-9c51769ca946&identityId=43aeaf10-3e2d-406e-bb78-2f3f9d7c3e4d
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: ez8edWrQXvay7P5LQlXA18UNSFwrf_ICbchfH9q3ldNXuElIGgZ_F1y2PZef35oucHj04_JvZWRJSMovCK47feOPoLFv2it6